version: "2"
volumes:
  postgres_data:
    driver: local
  mongo_data:
    driver: local
services:
  boilerplate-api:
    build: .
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - KEY_CLOAK_CLIENT_ID=main-keycloak-client
      - KEY_CLOAK_REALM_NAME=MainAdminRealm
      - KEY_CLOAK_REALM_PUBLIC_KEY=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCrVrCuTtArbgaZzL1hvh0xtL5mc7o0NqPVnYXkLvgcwiC3BjLGw1tGEGoJaXDuSaRllobm53JBhjx33UNv+5z/UMG4kytBWxheNVKnL6GgqlNabMaFfPLPCF8kAgKnsi79NMo+n6KnSY8YeUmec/p2vjO2NjsSAVcWEQMVhJ31LwIDAQAB
      - KEY_CLOAK_AUTH_SERVER_URL=http://localhost:8080/auth
      - KEY_CLOAK_SSL_REQUIRED=external
      - KEY_CLOAK_PUBLIC_CLIENT=true
      - KEY_CLOAK_CONFIDENTIAL_PORT=0
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - keycloak
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
  postgres:
      image: postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
  keycloak:
    image: wizzn/keycloak:14
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
    ports:
      - 8080:8080
    depends_on:
      - postgres