version: "3"

volumes:
  postgres_data:
    driver: local

services:
  admin-panel-api:
    build:
      context: ./admin-panel-api
      dockerfile: Dockerfile.prod
    ports:
      - "9000:9000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - KEY_CLOAK_CLIENT_ID=my-react-client
      - KEY_CLOAK_REALM_NAME=MyDemo
      - KEY_CLOAK_REALM_PUBLIC_KEY=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtZKEqacYI160ce569QJUpw25oH2hUQ5ZLsP3yGXs/dS2zaPf8U1KxAEi7JEM7LXOiAQOOT27iVfoQcKQkEY4u5MYCIMnI5p+FSGLw2LkcGAyAC23CeV/8fMT4vz5bI/8WIfPYxr+grfWYNnWT3GODaCxnFISgnzlW+aA/LHSDqZ4vi40lMKrBVqgI4kt73KG+EIa3by+qsF21wwLCaLg86CeW8Ua42nrU+wNxsetsANSzG5EZe13iMeZ4WqLUyRvCMrqY0VPT2/GNtiSoUSTZ5udS+zLOn8OIT7nUS+WubH+1xIFUIn/B9woLJ10s3UJRIz07UGixwbj8J4n5eI79wIDAQAB
      - KEY_CLOAK_AUTH_SERVER_URL=http://localhost:8080/auth
      - KEY_CLOAK_SSL_REQUIRED=external
      - KEY_CLOAK_PUBLIC_CLIENT=true
      - KEY_CLOAK_CONFIDENTIAL_PORT=0
  admin-panel:
    build:
      context: ./admin-panel
      dockerfile: Dockerfile.prod
      args:
        - REACT_APP_KEY_CLOAK_CLIENT_ID=my-react-client
        - REACT_APP_KEY_CLOAK_REALM_NAME=MyDemo
        - REACT_APP_KEY_CLOAK_AUTH_SERVER_URL=http://localhost:8080/auth
        - REACT_APP_KEY_CLOAK_SSL_REQUIRED=external
        - REACT_APP_KEY_CLOAK_PUBLIC_CLIENT=true
        - REACT_APP_KEY_CLOAK_CONFIDENTIAL_PORT=0
        - REACT_APP_BACKEND_BASE_URL=http://localhost:9000
    ports:
      - "3000:80"
    volumes:
      - ./admin-panel/src:/app/src
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
    ports:
      - 8080:8080
    depends_on:
      - postgres
