version: "3"

volumes:
  postgres_data:
    driver: local

services:
  admin-panel:
    build:
      context: ./admin-panel
      dockerfile: Dockerfile.prod
      args:
        - REACT_APP_NAME=PRODDD!
    ports:
      - "3000:3000"
    volumes:
      - ./admin-panel/src:/app/src
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
    ports:
      - 8080:8080
    depends_on:
      - postgres
