version: "3"

volumes:
  postgres_data:
    driver: local

services:
  admin-panel:
    build:
      context: ./admin-panel
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./admin-panel/src:/app/src
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_KEY_CLOAK_CLIENT_ID=my-react-client
      - REACT_APP_KEY_CLOAK_REALM_NAME=MyDemo
      - REACT_APP_KEY_CLOAK_AUTH_SERVER_URL=http://localhost:8080/auth
      - REACT_APP_KEY_CLOAK_SSL_REQUIRED=external
      - REACT_APP_KEY_CLOAK_PUBLIC_CLIENT=true
      - REACT_APP_KEY_CLOAK_CONFIDENTIAL_PORT=0
      - REACT_APP_BACKEND_BASE_URL=http://localhost:9000
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
    ports:
      - 8080:8080
    depends_on:
      - postgres
